# Generated by Django 4.0.6 on 2025-06-13 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=72, unique=True)),
                ('thumbnail_image', models.FileField(blank=True, null=True, upload_to='thumbnails/')),
                ('grade', models.IntegerField(blank=True, choices=[(9, '9th Grade'), (10, '10th Grade'), (11, '11th Grade'), (12, '12th Grade')], null=True)),
                ('subject', models.CharField(blank=True, choices=[('SCI', 'Science'), ('DMAT', 'Digital Media Arts & Technology'), ('ENGR', 'Engineering'), ('ARTS', 'Unified Arts & Music'), ('MATH', 'Mathematics'), ('ELA', 'English Language Arts'), ('SST', 'Social Studies'), ('LANG', 'World Language'), ('HPE', 'Health & Physical Education'), ('XCUR', 'Extracurricular Activity')], max_length=4)),
                ('skill', models.CharField(blank=True, choices=[('problem-solving', 'Problem Solving and Critical Thinking'), ('analyzing-info', 'Accessing and Analyzing Information'), ('communication', 'Communication and Collaboration'), ('creativity', 'Creativity and Innovation'), ('initiative', 'Initiative, Self-Direction, and Accountability'), ('citizenship', 'Citizenship and Responsibility')], max_length=15)),
                ('html_filename', models.CharField(blank=True, default='', help_text='Leave blank unless using a custom HTML file for this page', max_length=72)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('H', 'Heading'), ('P', 'Paragraph'), ('A', 'Link'), ('I', 'Image File'), ('Y', 'YouTube Video'), ('D', 'Downloadable File'), ('R', 'Raw HTML')], default='P', max_length=1)),
                ('text', models.TextField(blank=True, help_text='Use this for heading or paragraph text, for the clickable text for links, the alt text for images, and for all of the raw HTML for custom elements')),
                ('url', models.URLField(blank=True, help_text="For YouTube videos, paste the regular 'watch' URL. For links, use the full web address.", null=True)),
                ('file', models.FileField(blank=True, help_text='Upload your image or downloadable file.', null=True, upload_to='page_assets/')),
                ('width', models.CharField(blank=True, help_text='Leave blank for default element width. Define (in px or %) for images or other elements you want to customize.', max_length=10)),
                ('inline', models.BooleanField(default=False, help_text='Check to allow this component to display side-by-side with another (space permitting).')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='core.page')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
