# Generated by Django 4.0.6 on 2025-06-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.CharField(choices=[('H', 'Heading'), ('S', 'Subheading'), ('P', 'Paragraph'), ('A', 'Link'), ('I', 'Image File'), ('Y', 'YouTube Video'), ('D', 'Downloadable File'), ('R', 'Raw HTML')], default='P', max_length=1),
        ),
    ]
