# Generated by Django 4.0.6 on 2025-06-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_component_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.CharField(choices=[('H', 'Heading'), ('S', 'Subheading'), ('P', 'Paragraph'), ('A', 'Link'), ('I', 'Image File'), ('B', 'Multiple Images (Start)'), ('E', 'Multiple Images (End)'), ('Y', 'YouTube Video'), ('D', 'Downloadable File'), ('R', 'Raw HTML')], default='P', max_length=1),
        ),
    ]
