from django.db import models

import re

# This file defines how portfolio data will be organized and stored in your website's database
# Anytime you edit this file, you will likely need to rerun the 'makemigrations' and 'migrate' console commands

class Page(models.Model):
    title = models.CharField(max_length=255)  # displayed in browser tab and as large top-of-page heading
    slug = models.SlugField(max_length=72, unique=True)  # autogenerated (but still editable) url-friendly version of title
    thumbnail_image = models.FileField(upload_to='thumbnails/', null=True, blank=True) # image representing page

    class Grade(models.IntegerChoices):
        NINE =    9, '9th Grade'
        TEN =    10, '10th Grade'
        ELEVEN = 11, '11th Grade'
        TWELVE = 12, '12th Grade'

    grade = models.IntegerField(choices=Grade.choices, null=True, blank=True)

    class Subject(models.TextChoices):
        SCIENCE =      'SCI', 'Science'
        TECHNOLOGY =  'DMAT', 'Digital Media Arts & Technology'
        ENGINEERING = 'ENGR', 'Engineering'
        ARTS =        'ARTS', 'Unified Arts & Music'
        MATH =        'MATH', 'Mathematics'
        ENGLISH =      'ELA', 'English Language Arts'
        SOC_STUDIES =  'SST', 'Social Studies'
        LANGUAGE =    'LANG', 'World Language'
        HEALTH =       'HPE', 'Health & Physical Education'
        EXTRACURR =   'XCUR', 'Extracurricular Activity'

    subject = models.CharField(max_length=4, choices=Subject.choices, blank=True)

    class Skill(models.TextChoices):
        PROBLEM_SOLVING = 'problem-solving', 'Problem Solving and Critical Thinking'
        ANALYZING_INFO =   'analyzing-info', 'Accessing and Analyzing Information'
        COMMUNICATION =     'communication', 'Communication and Collaboration'
        CREATIVITY =           'creativity', 'Creativity and Innovation'
        INITIATIVE =           'initiative', 'Initiative, Self-Direction, and Accountability'
        CITIZENSHIP =         'citizenship', 'Citizenship and Responsibility'

    skill = models.CharField(max_length=15, choices=Skill.choices, blank=True)

    html_filename = models.CharField(default='', max_length=72, blank=True, help_text="Leave blank unless using a custom HTML file for this page")

    def __str__(self):
        return self.title


class Component(models.Model):

    page = models.ForeignKey(Page, on_delete=models.CASCADE, related_name='components')
    position = models.PositiveIntegerField(default=0)

    class Category(models.TextChoices):
        HEADING   =       'H', 'Heading'
        SUBHEADING =      'S', 'Subheading'
        PARAGRAPH =       'P', 'Paragraph'
        LINK =            'A', 'Link'
        IMAGE =           'I', 'Image File'
        GROUPIMAGEBEGIN = 'B', 'Multiple Images (Start)'
        GROUPIMAGEEND =   'E', 'Multiple Images (End)'
        YOUTUBE =         'Y', 'YouTube Video'
        DOWNLOAD =        'D', 'Downloadable File'
        HTML =            'R', 'Raw HTML'

    category = models.CharField(max_length=1, choices=Category.choices, default=Category.PARAGRAPH)

    text = models.TextField(blank=True, help_text='Use this for heading or paragraph text, for the clickable text for links, the alt text for images, and for all of the raw HTML for custom elements')
    url = models.URLField(null=True, blank=True, help_text="For YouTube videos, paste the regular 'watch' URL. For links, use the full web address.")
    file = models.FileField(upload_to='page_assets/', null=True, blank=True, help_text='Upload your image or downloadable file.')
    width = models.CharField(max_length=10, blank=True, help_text='Leave blank for default element width. Define (in px or %) for images or other elements you want to customize.')
    inline = models.BooleanField(default=False, help_text="Check to allow this component to display side-by-side with another (space permitting).")


    # This re or "Regex" (Regular Expression) code basically finds and pulls out
    # the unique character sequence from the user/admin-provided YouTube link.
    # It then makes available a properly-formatted embeddable URL for that video.
    @property
    def youtube_embed_url(self):
        if self.category != self.Category.YOUTUBE or not self.url:
            return ""

        video_id_match = re.search(r'(?:v=|/|embed/)([^&?/\s]{11})', self.url)

        if video_id_match:
            video_id = video_id_match.group(1)
            return f'https://www.youtube.com/embed/{video_id}'

        return ''


    class Meta:
        # Sets the components to be automatically sorted by their 'position' value
        ordering = ['position']

    def __str__(self):
        # Prettier short text representation of each component (based on page slug and component type/position)
        formatted_slug = self.page.slug.replace('-', ' ').title()
        return f"{formatted_slug} ({self.position}) - {self.get_category_display()}"